# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1563a2fc50072d0d3cb489a48e31e883564c89f158ca7d78d9834ea53cc99a07d1623b58c15863e8ed432df64e8064e855aa30d42f5b1839296fd00fe8120a20

test:
  secret_key_base: fa9906b971b962863abec27b9f814ef694723c0ce3df92aee75024a7c9b440cab4867151eec5ff3f555c22dd6fbe11535023726595067f3b19f320f222ec2e9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
